### ISSUE TITLE
fopen not being checked for failed open

### ISSUE THREAD

**Issue by ColinIanKing** [Rajaram-Regupathy/libtypec#10]
function get_opr_mode() is opening a file and not checking for a NULL fp on file open failure:

```
        FILE *fp = fopen(path, "r");

        fgets(buf, 64, fp);

...

       fclose(fp);
```

This will end up with NULL pointer dereferencing (and SIGSEGV faults).

Same for function get_cable_plug_type(), get_cable_type() and get_cable_mode_support()

**Comment by Rajaram-Regupathy** [comment]
Fixed Thanks
