### ISSUE TITLE
missing return from libtypec_exit()

### ISSUE THREAD

**Issue by ColinIanKing** [Rajaram-Regupathy/libtypec#19]
Function libtypec_exit returns a value only when the if statement is true. There is no explicit return value on the false path of the if statement.   

The code is currently effectively this logic:

{
   if (condition)
         return cur_libtypec_os_backend->exit();

  /* missing return value in this code path  */
}

Unfortunately the condition check checks if cur_libtypec_os_backend->exit  is null and will call the function if the pointer is null. So this looks wrong to me.

```
int libtypec_exit(void)
{
    if (!cur_libtypec_os_backend || !cur_libtypec_os_backend->exit )
    /* clear session info */
 
    return cur_libtypec_os_backend->exit();
}
```

**Comment by Rajaram-Regupathy** [comment]
resolved
