### ISSUE TITLE
potential time of check of use (TOCTOU) issue with lstat on path_str and then opening the directory on path_str in ibtypec_sysfs_get_pdos_ops

### ISSUE THREAD

**Issue by ColinIanKing** [Rajaram-Regupathy/libtypec#25]
In function libtypec_sysfs_get_pdos_ops there is an lstat check followed by a later opendir on path_str.  Stringent security code checkers complain that the directory may have changed (e.g. renamed or replaced) between the lstat and opendir.  Personally I don't think this specific case needs to be worried about, but one could actually remove the lstat because if the path does not exist the opendir() will certainly catch this failure case. So it may be worth doing:

```
typec_path = opendir(path_str);
if (!typec_path) {
        printf("Incorrect connector number : failed to open, %s", path_str);
        return -1;
} 
```

and removing the lstat().  Also should error messages be fprinting to stderr?

**Comment by Rajaram-Regupathy** [comment]
Added for argument checking for better error reporting. Will analyze more

**Comment by Rajaram-Regupathy** [comment]
fixed
