### ISSUE TITLE
DFP devices being misclassified as UFP devices

### ISSUE THREAD

**Issue by jthiesatgoogle** [Rajaram-Regupathy/libtypec#3]
Currently DFP devices will be misclassified as UFP devices. This is because of an incorrect signal assignment in get_partner_product_type. Fix is here: [https://github.com/jthiesatgoogle/libtypec-1/commit/f5b9e88d8c55259d89cd640d70127fb710cec415](https://github.com/jthiesatgoogle/libtypec-1/commit/f5b9e88d8c55259d89cd640d70127fb710cec415)

**Comment by Rajaram-Regupathy** [comment]
resolved
